/** Mirrors Rust scanner::file_info::Language */
export type Language =
  | "rust"
  | "typeScript"
  | "javaScript"
  | "python"
  | "go"
  | "java"
  | "c"
  | "cpp"
  | "cSharp"
  | "ruby"
  | "swift"
  | "kotlin"
  | "php"
  | "scala"
  | "shell"
  | "lua"
  | "zig"
  | "elixir"
  | "haskell"
  | "ocaml"
  | "dart"
  | "html"
  | "css"
  | "sql"
  | "markdown"
  | "toml"
  | "yaml"
  | "json"
  | { other: string };

/** Mirrors Rust scanner::file_info::FileInfo */
export interface FileInfo {
  path: string;
  relativePath: string;
  language: Language | null;
  sizeBytes: number;
  lineCount: number;
  isBinary: boolean;
  contentHash: number;
}

/** Mirrors Rust scanner::discovery::LanguageStats */
export interface LanguageStats {
  language: Language;
  fileCount: number;
  totalLines: number;
  totalBytes: number;
}

/** Mirrors Rust scanner::discovery::ProjectSummary */
export interface ProjectSummary {
  path: string;
  name: string;
  projectType: string;
  hasReadme: boolean;
}

/** Mirrors Rust scanner::discovery::ProjectManifest */
export interface ProjectManifest {
  id: string;
  rootPath: string;
  name: string;
  description: string;
  languages: LanguageStats[];
  files: FileInfo[];
  totalSizeBytes: number;
  totalLines: number;
  fileCount: number;
  projectType: string;
}

/** Pipeline generation status */
export type GenerationStatus =
  | "idle"
  | { running: { projectId: string; phase: string } }
  | { complete: { projectId: string } }
  | { error: { message: string } };

/** Output format identifiers */
export type OutputFormat =
  | "openAI"
  | "chatML"
  | "llama4"
  | "mistral"
  | "shareGPT"
  | "alpaca";

/** Export mode */
export type ExportMode = "conversational" | "agentic";

/** Sample types */
export type SampleType =
  | "codeQA"
  | "codeCompletion"
  | "toolCalling"
  | "multiTurn"
  | "documentation"
  | "bugDetection"
  | "repoContext";

/** Quality filtering config */
export interface QualityConfig {
  minLineCount: number;
  maxLineCount: number;
  maxAvgLineLength: number;
  minAlphanumericFraction: number;
  dedupJaccardThreshold: number;
  minTokensPerSample: number;
  maxTokensPerSample: number;
  skipAutogenerated: boolean;
}

/** Ignore patterns config */
export interface IgnoreConfig {
  useGitignore: boolean;
  defaultPatterns: string[];
  userPatterns: string[];
  maxFileSizeBytes: number;
  skipBinary: boolean;
}

/** Generation config */
export interface GenerationConfig {
  enabledTypes: SampleType[];
  exportMode: ExportMode;
  tokenBudget: number;
  maxContextTokens: number;
  samplesPerFunction: number;
  includeReasoning: boolean;
}

/** Export config */
export interface ExportConfig {
  outputDirectory: string;
  splitByFormat: boolean;
  includeManifest: boolean;
  includeStatistics: boolean;
}

/** Full pipeline config */
export interface PipelineConfig {
  ignore: IgnoreConfig;
  outputFormats: OutputFormat[];
  quality: QualityConfig;
  generation: GenerationConfig;
  export: ExportConfig;
}

/** Format metadata for UI */
export interface FormatInfo {
  format: OutputFormat;
  name: string;
  description: string;
  models: string[];
  supportsTools: boolean;
}

/** Pipeline phases */
export type PipelinePhase =
  | "scanning"
  | "analyzing"
  | "generating"
  | "qualityFiltering"
  | "formatting"
  | "exporting";

/** Progress events streamed from the pipeline */
export type ProgressEvent =
  | { event: "pipelineStarted"; data: { projectId: string; projectName: string; totalFiles: number } }
  | { event: "phaseStarted"; data: { phase: PipelinePhase; totalItems: number } }
  | { event: "phaseProgress"; data: { phase: PipelinePhase; completed: number; total: number; currentItem: string | null } }
  | { event: "phaseCompleted"; data: { phase: PipelinePhase; durationMs: number; itemsProcessed: number } }
  | { event: "samplesGenerated"; data: { count: number; byType: [string, number][] } }
  | { event: "qualityReport"; data: { totalSamples: number; passed: number; filtered: number; duplicatesRemoved: number } }
  | { event: "exportProgress"; data: { format: string; samplesWritten: number; totalSamples: number } }
  | { event: "pipelineCompleted"; data: { totalDurationMs: number; totalSamples: number; outputFiles: string[] } }
  | { event: "pipelineError"; data: { message: string; phase: PipelinePhase | null } };

/** Result of a pipeline run */
export interface PipelineResult {
  projectId: string;
  totalSamples: number;
  samplesByType: Record<string, number>;
  qualityStats: QualityStats;
  outputFiles: string[];
  totalDurationMs: number;
}

export interface QualityStats {
  totalInput: number;
  passed: number;
  filtered: number;
  duplicatesRemoved: number;
  preDedupCount: number;
}

/** Dataset statistics */
export interface DatasetStatistics {
  totalSamples: number;
  samplesByType: Record<string, number>;
  samplesByLanguage: Record<string, number>;
  tokenStats: TokenStats;
  complexityDistribution: Record<string, number>;
}

export interface TokenStats {
  min: number;
  max: number;
  mean: number;
  median: number;
  p90: number;
  p99: number;
  total: number;
}
