use serde::{Deserialize, Serialize};

use crate::scanner::walker::DEFAULT_IGNORE_PATTERNS;

/// Top-level pipeline configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PipelineConfig {
    pub ignore: IgnoreConfig,
    pub output_formats: Vec<OutputFormat>,
    pub quality: QualityConfig,
    pub generation: GenerationConfig,
    pub export: ExportConfig,
}

impl Default for PipelineConfig {
    fn default() -> Self {
        Self {
            ignore: IgnoreConfig::default(),
            output_formats: vec![OutputFormat::OpenAI, OutputFormat::ChatML],
            quality: QualityConfig::default(),
            generation: GenerationConfig::default(),
            export: ExportConfig::default(),
        }
    }
}

/// Ignore patterns configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IgnoreConfig {
    pub use_gitignore: bool,
    pub default_patterns: Vec<String>,
    pub user_patterns: Vec<String>,
    pub max_file_size_bytes: u64,
    pub skip_binary: bool,
}

impl Default for IgnoreConfig {
    fn default() -> Self {
        Self {
            use_gitignore: true,
            default_patterns: DEFAULT_IGNORE_PATTERNS
                .iter()
                .map(|s| s.to_string())
                .collect(),
            user_patterns: Vec::new(),
            max_file_size_bytes: 1_000_000,
            skip_binary: true,
        }
    }
}

/// Supported output formats for training data.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum OutputFormat {
    OpenAI,
    ChatML,
    Llama4,
    Mistral,
    ShareGPT,
    Alpaca,
}

impl std::fmt::Display for OutputFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::OpenAI => write!(f, "OpenAI Chat"),
            Self::ChatML => write!(f, "ChatML/Hermes"),
            Self::Llama4 => write!(f, "Llama 4"),
            Self::Mistral => write!(f, "Mistral"),
            Self::ShareGPT => write!(f, "ShareGPT"),
            Self::Alpaca => write!(f, "Alpaca"),
        }
    }
}

/// Export mode: conversational (text-only) vs agentic (with tool use).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ExportMode {
    /// Clean text-only exchanges, no tool noise.
    Conversational,
    /// Full structured tool use with proper function-calling schema.
    Agentic,
}

/// Training data sample types to generate.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum SampleType {
    CodeQA,
    CodeCompletion,
    ToolCalling,
    MultiTurn,
    Documentation,
    BugDetection,
    RepoContext,
}

/// Quality filtering configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QualityConfig {
    pub min_line_count: usize,
    pub max_line_count: usize,
    pub max_avg_line_length: usize,
    pub min_alphanumeric_fraction: f64,
    pub dedup_jaccard_threshold: f64,
    pub min_tokens_per_sample: usize,
    pub max_tokens_per_sample: usize,
    pub skip_autogenerated: bool,
}

impl Default for QualityConfig {
    fn default() -> Self {
        Self {
            min_line_count: 3,
            max_line_count: 10_000,
            max_avg_line_length: 200,
            min_alphanumeric_fraction: 0.4,
            dedup_jaccard_threshold: 0.85,
            min_tokens_per_sample: 50,
            max_tokens_per_sample: 8192,
            skip_autogenerated: true,
        }
    }
}

/// Generation configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GenerationConfig {
    pub enabled_types: Vec<SampleType>,
    pub export_mode: ExportMode,
    /// Maximum tokens per example. Conversations are chunked to fit.
    pub token_budget: usize,
    pub max_context_tokens: usize,
    pub samples_per_function: usize,
    pub include_reasoning: bool,
}

impl Default for GenerationConfig {
    fn default() -> Self {
        Self {
            enabled_types: vec![
                SampleType::CodeQA,
                SampleType::CodeCompletion,
                SampleType::ToolCalling,
                SampleType::MultiTurn,
                SampleType::Documentation,
            ],
            export_mode: ExportMode::Agentic,
            token_budget: 8192,
            max_context_tokens: 4096,
            samples_per_function: 1,
            include_reasoning: false,
        }
    }
}

/// Export configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExportConfig {
    pub output_directory: String,
    pub split_by_format: bool,
    pub include_manifest: bool,
    pub include_statistics: bool,
}

impl Default for ExportConfig {
    fn default() -> Self {
        Self {
            output_directory: String::new(), // Set by user via dialog
            split_by_format: true,
            include_manifest: true,
            include_statistics: true,
        }
    }
}

/// Metadata about an output format (for UI display).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FormatInfo {
    pub format: OutputFormat,
    pub name: String,
    pub description: String,
    pub models: Vec<String>,
    pub supports_tools: bool,
}

pub fn available_formats() -> Vec<FormatInfo> {
    vec![
        FormatInfo {
            format: OutputFormat::OpenAI,
            name: "OpenAI Chat".to_string(),
            description: "messages array with tool_calls. Universal standard.".to_string(),
            models: vec!["GPT-OSS".to_string(), "General".to_string()],
            supports_tools: true,
        },
        FormatInfo {
            format: OutputFormat::ChatML,
            name: "ChatML / Hermes".to_string(),
            description: "im_start/im_end delimiters with <tools> XML tags.".to_string(),
            models: vec!["Qwen3".to_string(), "Qwen3.5".to_string(), "Phi-4".to_string()],
            supports_tools: true,
        },
        FormatInfo {
            format: OutputFormat::Llama4,
            name: "Llama 4".to_string(),
            description: "header_start/header_end tokens with pythonic tool calls.".to_string(),
            models: vec!["Llama Scout".to_string(), "Llama Maverick".to_string()],
            supports_tools: true,
        },
        FormatInfo {
            format: OutputFormat::Mistral,
            name: "Mistral".to_string(),
            description: "INST control tokens with JSON tool_calls.".to_string(),
            models: vec!["Mistral Small".to_string(), "Mistral Large".to_string()],
            supports_tools: true,
        },
        FormatInfo {
            format: OutputFormat::ShareGPT,
            name: "ShareGPT".to_string(),
            description: "Legacy conversations format for LlamaFactory/Unsloth.".to_string(),
            models: vec!["LlamaFactory".to_string(), "Unsloth".to_string()],
            supports_tools: false,
        },
        FormatInfo {
            format: OutputFormat::Alpaca,
            name: "Alpaca".to_string(),
            description: "Simple instruction/input/output triplets.".to_string(),
            models: vec!["Any instruction-tuned model".to_string()],
            supports_tools: false,
        },
    ]
}
