/// Detect if a file appears to be auto-generated or boilerplate.
/// Returns true if the file should be skipped.
pub fn is_autogenerated(content: &str, file_path: &str) -> bool {
    // Check filename patterns
    let lower_path = file_path.to_lowercase();
    if lower_path.contains("generated")
        || lower_path.contains("autogen")
        || lower_path.contains(".gen.")
        || lower_path.ends_with(".pb.go")
        || lower_path.ends_with(".pb.rs")
        || lower_path.ends_with(".d.ts")
        || lower_path.ends_with(".min.js")
        || lower_path.ends_with(".min.css")
        || lower_path.ends_with(".bundle.js")
    {
        return true;
    }

    // Check file content markers (first 20 lines)
    let header: String = content.lines().take(20).collect::<Vec<&str>>().join("\n");
    let lower_header = header.to_lowercase();

    let gen_markers = [
        "auto-generated",
        "autogenerated",
        "automatically generated",
        "do not edit",
        "do not modify",
        "generated by",
        "generated from",
        "this file is generated",
        "code generated by",
        "@generated",
        "machine generated",
        "this is a generated file",
    ];

    for marker in &gen_markers {
        if lower_header.contains(marker) {
            return true;
        }
    }

    // Check for lock file patterns (high entropy, repetitive structure)
    if lower_path.ends_with(".lock")
        || lower_path.contains("lock.")
        || lower_path == "package-lock.json"
        || lower_path == "yarn.lock"
        || lower_path == "pnpm-lock.yaml"
        || lower_path == "cargo.lock"
        || lower_path == "poetry.lock"
        || lower_path == "pipfile.lock"
        || lower_path == "bun.lockb"
    {
        return true;
    }

    false
}

/// Check if a training sample's source code looks like boilerplate.
pub fn is_boilerplate_code(source: &str) -> bool {
    let lines: Vec<&str> = source.lines().collect();
    if lines.is_empty() {
        return true;
    }

    // Very short functions are often getters/setters
    if lines.len() <= 3 {
        let text = source.to_lowercase();
        if text.contains("get") || text.contains("set") || text.contains("return self.") {
            return true;
        }
    }

    // Check for high comment-to-code ratio (mostly comments)
    let comment_lines = lines
        .iter()
        .filter(|l| {
            let trimmed = l.trim();
            trimmed.starts_with("//")
                || trimmed.starts_with('#')
                || trimmed.starts_with("/*")
                || trimmed.starts_with('*')
        })
        .count();

    if lines.len() > 5 && comment_lines as f64 / lines.len() as f64 > 0.7 {
        return true;
    }

    false
}
